# Generated by Django 4.2.21 on 2025-05-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutualfund',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='aum',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='benchmark_index',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='cagr',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='expense_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='fund_house',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='fund_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='isin',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='nfo_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='returns_1yr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='returns_3yr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='returns_5yr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='risk_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='scheme_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='size',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='current_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='free_cash',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='invested_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='profit_loss',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='profit_loss_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='total_exchange_traded_funds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='total_mutual_funds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='total_stocks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='portfoliomutualfund',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='portfoliomutualfund',
            name='amount_invested',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='portfoliomutualfund',
            name='average_nav',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='portfoliomutualfund',
            name='current_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='portfoliomutualfund',
            name='invested_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfoliomutualfund',
            name='investment_type',
            field=models.CharField(choices=[('SIP', 'SIP'), ('Lump Sum', 'Lump Sum')], default='SIP', max_length=50),
        ),
        migrations.AddField(
            model_name='portfoliomutualfund',
            name='last_invested_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfoliomutualfund',
            name='profit_loss',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='portfoliomutualfund',
            name='profit_loss_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='portfoliostock',
            name='added_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='portfoliostock',
            name='amount_invested',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='portfoliostock',
            name='average_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='portfoliostock',
            name='current_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='portfoliostock',
            name='last_added_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='portfoliostock',
            name='profit_loss',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='portfoliostock',
            name='profit_loss_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='stock',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='all_time_high',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='all_time_low',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='average_volume',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='code',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='day_high',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='day_low',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='dividend_yield',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='industry',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='stock',
            name='ipo_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='isin',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='last_traded_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='stock',
            name='market_cap',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='stock',
            name='open_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='pe_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='previous_close',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='sector',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='stock',
            name='stock_exchange',
            field=models.CharField(default='NSE', max_length=50),
        ),
        migrations.AddField(
            model_name='stock',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='volume',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='week_52_high',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='week_52_low',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='mutualfund',
            name='current_nav',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='name',
            field=models.CharField(blank=True, default='My Portfolio', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='portfoliostock',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
